// User
export const LOGIN_WITH_EMAIL = "LOGIN_WITH_EMAIL";
export const SIGNUP_WITH_EMAIL = "SIGNUP_WITH_EMAIL";
export const LOGOUT = "LOGOUT";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_USER_METRICS_DATA = "UPDATE_USER_METRICS_DATA";
export const UPDATE_EMAIL_SUCCESS = "UPDATE_EMAIL_SUCCESS";
export const REAUTHENTICATION_SUCCESS = "REAUTHENTICATION_SUCCESS";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";

// Auth
export const AuthActionTypes = {
  LOGIN_WITH_EMAIL: "LOGIN_WITH_EMAIL",
  SIGNUP_WITH_EMAIL: "SIGNUP_WITH_EMAIL",
  LOGOUT: "LOGOUT",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  UPDATE_EMAIL_SUCCESS: "UPDATE_EMAIL_SUCCESS",
  REAUTHENTICATION_SUCCESS: "REAUTHENTICATION_SUCCESS",
  UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
};

// Toast
export const ToastTypes = {
  SHOW_TOAST: "showToast",
  SHOW_ERROR_TOAST: "showErrorToast",
  DISCARD_TOAST: "discardToast",
};

// Device
export const GET_DEVICES = "GET_DEVICES";
export const GET_DEVICE = "GET_DEVICE";
export const ADD_DEVICE = "ADD_DEVICE";
export const UPDATE_DEVICE = "UPDATE_DEVICE";
export const DELETE_DEVICE = "DELETE_DEVICE";

// Settings
export const USER_METRICS_DATA_MODAL_VISIBLE =
  "USER_METRICS_DATA_MODAL_VISIBLE";
export const DARK_THEME = "DARK_THEME";
export const MEASUREMENT_SYSTEM = "MEASUREMENT_SYSTEM"; // US or Metric
export const UPDATE_ACTIVITY_RINGS_DATA = "UPDATE_ACTIVITY_RINGS_DATA";
