export const LOGIN_WITH_EMAIL = "LOGIN_WITH_EMAIL";
export const SIGNUP_WITH_EMAIL = "SIGNUP_WITH_EMAIL";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const AuthActionTypes = {
  LOGIN_WITH_EMAIL: "LOGIN_WITH_EMAIL",
  SIGNUP_WITH_EMAIL: "SIGNUP_WITH_EMAIL",
  LOGOUT: "LOGOUT",
  AUTH_ERROR: "AUTH_ERROR",
  UPDATE_PROFILE: "UPDATE_PROFILE",
};

export const ToastTypes = {
  SHOW_TOAST: "showToast",
  SHOW_ERROR_TOAST: "showErrorToast",
  DISCARD_TOAST: "discardToast",
};

export const DeviceActionTypes = {
  GET_DEVICES: "GET_DEVICES",
  GET_DEVICE: "GET_DEVICE",
  ADD_DEVICE: "ADD_DEVICE",
  UPDATE_DEVICE: "UPDATE_DEVICE",
  DELETE_DEVICE: "DELETE_DEVICE",
};
