name: Test React Native App testing

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [testing]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install
        working-directory: SmartClothingApp

      - name: Run Tests
        run: npm run test
        working-directory: SmartClothingApp

      - name: Count Tests
        id: count-tests
        run: echo "::set-output name=number_of_tests::$(grep -oP '(?<=Test Suites: ).*(?= passed)' SmartClothingApp/__tests__/*.test.js | awk '{total += $1} END {print total}')"

      - name: Success Message
        if: success()
        run: |
          echo "Regression testing successfully executed!"
          echo "Number of tests executed: ${{ steps.count-tests.outputs.number_of_tests }}"
          echo "Time taken to execute: ${{ steps.tests.outputs.execution_time }} seconds"
